site_name: SPHinXsim

nav:
  - Home: index.md
  - Installation:
      - Overview: installation.md
      - Linux: installation-linux.md
      - Windows: installation-windows.md
      - macOS: installation-macos.md
  - CLI Usage: cli-usage.md
  - Visualization: visualization.md
  - LLM Testing: llm-testing.md
  - Theoretical Backgrounds:
      - Overview: theoretical-background.md
      - Physical Models: theoretical-background-physical-models.md
      - SPH Methods: theoretical-background-sph-methods.md

theme:
  name: material
  favicon: images/logo-16x16.ico
  logo: images/logo-white.png

  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.highlight

  palette:
    - scheme: default
      primary: blue
      accent: indigo
font:
  text: Roboto
  code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
