site_name: SPHinXsim

theme:
  name: material
  favicon: images/logo-16x16.ico
  logo: images/logo.png

  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.highlight

  palette:
    - scheme: default
      primary: blue
      accent: indigo
font:
  text: Roboto
  code: Roboto Mono

  markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js    